<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="12.1.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Kreisverkehr.NetUpnp" Version="0.1.0" />
    <PackageReference Include="Kreisverkehr.NetSsdp" Version="0.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
  </ItemGroup>

</Project>
